export const DASHBOARDTWEETS = 'DASHBOARDTWEETS';
export const CURRENTTWEET = 'CURRENTTWEET';
export const SETPAGENUM = 'SETPAGENUM';
export const LISTTWEETS = 'LISTTWEETS';
export const BOOKMARKEDTWEETS= 'BOOKMARKEDTWEETS';
export const LIKESTWEETS = 'LIKESTWEETS';
export const REPLIESTWEETS = 'REPLIESTWEETS';
export const USERTWEETS = 'USERTWEETS';